server:
  port: 8080

spring:
  application:
    name: football-league
  datasource:
    url: "jdbc:mysql://localhost:3306/football_league"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true